package zy.cy6.dqyt.zygl.orders.command;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ZYADMIN' at '17-10-25 下午2:58' with Gradle 2.14.1
 *
 * @author ZYADMIN, @date 17-10-25 下午2:58
 */
public class PortfolioTest {
	
    @Test public void testSomeLibraryMethod() {
    	Portfolio classUnderTest = new Portfolio();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
}
