spring:
    profiles:
        active: dev
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        #datasource 使用HikariDataSource 时，一定是 jdbcUrl不能是url
        #加入AUTO_SERVER=TRUE 可以在web控制台中同时打开zygl,前题是当使用自动混合模式，所有客户端都需要使用同样的URL进行连接（不管它是一个本地还是一个远程连接。
#        jdbcUrl: jdbc:h2:mem:zygl;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;MODE=ORACLE;TRACE_LEVEL_FILE=3;DB_CLOSE_ON_EXIT=FALSE"
        jdbcUrl: jdbc:h2:c:/temp/zyglWeb;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true

#            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

    h2:
        console:
            enabled: true
server:
    port: 8080
